services:
  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otelcol:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - 4317:4317
      - 55679:55679
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service-a:
    build: ./service-a
    ports:
      - 8080:8080
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service-b:
    build: ./service-b
    environment:
      - DOTENV_PATH=.env
    ports:
      - 8081:8081
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    driver: bridge