# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "3.7"
services:
  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    networks:
      - example
networks:
  example: